name: Docker build
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - develop
jobs:
  docker:
    uses: usdot-fhwa-stol/actions/.github/workflows/docker.yml@main