name: Docker build
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - cf-890_ci_navigation2_ectension
jobs:
  docker:
    uses: usdot-fhwa-stol/actions/.github/workflows/docker.yml@main